### ISSUE TITLE
Mount of /dev/slccmtp01 ro /vol/storage_slccmtp01 failed

### ISSUE THREAD

**Issue by 0DanDan0** [GaryOderNichts/vWii-Decaffeinator#2]
whenever i start it i get this error plz help

**Comment by Ikeoth** [comment]
Same is happening to me, 5.6U on Aroma beta 22 Environment

**Comment by the-github-boi** [comment]
> Same is happening to me, 5.6U on Aroma beta 22 Environment

Same here, but my Wii U now show an error every time I boot it up.
Error Code: 160-0101

**Comment by 0DanDan0** [comment]
Anything yet?

**Comment by the-github-boi** [comment]
After troubleshooting,  my vwii still won’t boot and my Wii U is up to date.

**Comment by Andrew1Hawes** [comment]
In the ftpiiu plugin settings, disable system file access, and try again.

**Comment by 0DanDan0** [comment]
That fixed the issue thx
